### PR TITLE
feat: upgrade everything

### PR DESCRIPTION
**Pull request by swouf**
Upgrade all deps and the whole code to work with up-to-date packages.

### CODE REVIEW

**Comment by swouf** [comment]
There is a remaining issue related to the images, see #61. I will look into this later but feel free to see what can be done.

**Review by pyphilia — APPROVED** [review]
LGTM thank you for your work! Let me know when it's ready we'll prepare the workflows to deploy automatically.

**Comment by spaenleh** [comment]
I fixed the logos, images etc, the cookies banner theme too. 

Site should be 1:1 to the original, with very very small changes. I moved all logos to svg so some have been updated.

**Comment by swouf** [comment]
Just tested. Everything works and looks fine to me. Thanks @spaenleh for your work 🥂

**Pull request merged**
